"use client";
import { useEffect, useState, useTransition } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { getDocumentRelations,searchRelationDocuments,saveDocumentRelation,removeDocumentRelation,type DocumentRelationItem } from "../api/relation-actions";
import type { DocumentListItem,PagedResult } from "../model/document";
const labels:Record<string,string>={Related:"İlgili belge",Attachment:"Ek belge",PreviousDecision:"Önceki karar"};
const field="mt-1 block min-h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm";
export function DocumentRelations({documentId,canManage}:{documentId:string;canManage:boolean}) {
  const [items,setItems]=useState<DocumentRelationItem[]>([]);const [error,setError]=useState("");const [pending,start]=useTransition();const [revision,setRevision]=useState(0);
  const [editing,setEditing]=useState<DocumentRelationItem|null>(null);const [removing,setRemoving]=useState<DocumentRelationItem|null>(null);
  const [search,setSearch]=useState("");const [results,setResults]=useState<PagedResult<DocumentListItem>|null>(null);const [target,setTarget]=useState("");const [notice,setNotice]=useState("");
  useEffect(()=>{let active=true;start(async()=>{const result=await getDocumentRelations(documentId);if(active){setItems(result.items);setError(result.error??"");}});return()=>{active=false;};},[documentId,revision]);
  const find=(page:number)=>start(async()=>{setError("");setTarget("");const result=await searchRelationDocuments(search,page);setResults(result.data??null);setError(result.error??"");});
  return <section className="space-y-4 border-t border-border pt-4" aria-label="Belge ilişkileri"><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">İlgili belgeler</h3><Button size="sm" variant="outline" disabled={pending} onClick={()=>setRevision(v=>v+1)}>Yenile</Button></div>
    {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}{pending&&<p role="status" className="text-sm">İşlem sürüyor…</p>}
    {!pending&&!error&&!items.length&&<p className="text-sm text-muted-foreground">Bu belgeye bağlı ilgili belge yok.</p>}
    <ul className="space-y-3">{items.map(item=><li key={item.id} className="space-y-2 rounded-lg border border-border p-3 text-sm"><Link className="font-medium text-primary underline" href={`/documents/${item.sourceDocumentId===documentId?item.targetDocumentId:item.sourceDocumentId}`}>{item.title}</Link><p>{labels[item.kind]??item.kind}{item.sourceDocumentId!==documentId?" · Bu belgeye gelen bağlantı":""}</p><p className="whitespace-pre-wrap">{item.note}</p><p className="text-xs text-muted-foreground">{item.modifiedBy} · {new Date(item.modifiedAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</p>{item.canManage&&<div className="flex gap-2"><Button size="sm" variant="outline" disabled={pending} onClick={()=>{setEditing(item);setRemoving(null);setError("");}}>Düzenle</Button><Button size="sm" variant="outline" disabled={pending} onClick={()=>{setRemoving(item);setEditing(null);setError("");}}>Bağlantıyı kaldır</Button></div>}</li>)}</ul>
    {removing&&<form className="space-y-3 rounded-lg border border-border p-3" onSubmit={event=>{event.preventDefault();const reason=String(new FormData(event.currentTarget).get("reason")??"");start(async()=>{const result=await removeDocumentRelation(documentId,removing,reason);setError(result.error??"");if(!result.error){setRemoving(null);setRevision(v=>v+1);setNotice("İlişki kaldırıldı. Belgeler korundu.");}});}}><p className="text-sm font-medium">{removing.title} bağlantısını kaldır</p><label className="block text-sm">Gerekçe<textarea className={field} name="reason" required maxLength={1000}/></label><div className="flex gap-2"><Button type="submit" disabled={pending}>Bağlantıyı kaldır</Button><Button type="button" variant="outline" onClick={()=>setRemoving(null)}>Vazgeç</Button></div></form>}
    {canManage&&<details open={editing?true:undefined} className="rounded-lg border border-border p-3"><summary className="cursor-pointer text-sm font-medium">{editing?"İlişkiyi düzenle":"Belge ilişkilendir"}</summary><div className="mt-4 space-y-3">
      {!editing&&<><form className="flex items-end gap-2" onSubmit={event=>{event.preventDefault();find(1);}}><label className="min-w-0 flex-1 text-sm">Belge başlığı<input value={search} onChange={event=>setSearch(event.target.value)} className={field}/></label><Button type="submit" disabled={pending}>Ara</Button></form>{results&&<><label className="block text-sm">İlgili belge<select className={field} value={target} onChange={event=>setTarget(event.target.value)}><option value="">Belge seçin</option>{results.items.filter(item=>item.id!==documentId).map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="flex items-center justify-between gap-2 text-sm"><Button type="button" size="sm" variant="outline" disabled={pending||results.page<=1} onClick={()=>find(results.page-1)}>Önceki</Button><span>{results.page} / {Math.max(1,Math.ceil(results.totalCount/results.pageSize))}</span><Button type="button" size="sm" variant="outline" disabled={pending||results.page*results.pageSize>=results.totalCount} onClick={()=>find(results.page+1)}>Sonraki</Button></div></>}</>}
      <form key={editing?.id??"new"} className="space-y-3" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);start(async()=>{const result=await saveDocumentRelation(documentId,editing?.targetDocumentId??target,String(data.get("kind")),String(data.get("note")),editing?.id,editing?.version);setError(result.error??"");if(!result.error){setEditing(null);setTarget("");setRevision(v=>v+1);setNotice("Belge ilişkisi kaydedildi.");}});}}><label className="block text-sm">İlişki türü<select name="kind" defaultValue={editing?.kind??"Related"} className={field}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm">Açıklama<textarea name="note" defaultValue={editing?.note??""} required maxLength={1000} className={field}/></label><div className="flex gap-2"><Button type="submit" disabled={pending||(!editing&&!target)}>Kaydet</Button>{editing&&<Button type="button" variant="outline" onClick={()=>setEditing(null)}>Vazgeç</Button>}</div></form>
    </div></details>}
  </section>;
}
