"use client";
import { useEffect,useState,useTransition } from "react";
import { getDocumentProtection,type OriginalProtectionStatus } from "../api/protection-action";
export function DocumentProtection({documentId,version}:{documentId:string;version:number}) {
 const [items,setItems]=useState<OriginalProtectionStatus[]>([]);const [error,setError]=useState("");const [pending,start]=useTransition();
 useEffect(()=>{let active=true;start(async()=>{const result=await getDocumentProtection(documentId);if(active){setItems(result.items);setError(result.error??"");}});return()=>{active=false;};},[documentId]);
 const value=items.find(item=>item.versionNumber===version);const failed=error||value?.error;const verified=!!value?.checkedAt&&!failed;const locked=verified&&(value?.legalHold||!!value?.retainUntil&&new Date(value.retainUntil)>new Date());
 return <section className="mt-2 space-y-2 rounded-lg border border-border p-3 text-sm" aria-label="Dijital nesne koruması"><h3 className="font-semibold">Depo koruması · v{version}</h3>{pending?<p role="status">Doğrulama bilgisi yükleniyor…</p>:<><p className={failed?"font-medium text-destructive":"font-medium"}>{failed?"Koruma doğrulanamadı":locked?"Depo kilidi doğrulandı":verified?"Aktif depo kilidi yok":"Henüz doğrulanmadı"}</p>{failed&&<p role="alert" className="text-xs text-destructive">{failed}</p>}{value?.checkedAt&&<p className="text-xs text-muted-foreground">Son kontrol: {new Date(value.checkedAt).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul"})}</p>}{failed&&(value?.retainUntil||value?.legalHold)&&<p className="text-xs text-muted-foreground">Aşağıdaki değerler önceki başarılı doğrulamadan kalan bilgidir.</p>}{value?.retainUntil&&<p className="text-xs">Kaydedilmiş saklama sonu: {new Date(value.retainUntil).toLocaleDateString("tr-TR")}</p>}{value?.legalHold&&<p className="text-xs">Kaydedilmiş yasal bekletme: Açık</p>}{value?.storageVersionId&&<p className="break-all text-xs text-muted-foreground">Depo sürümü: {value.storageVersionId}</p>}{!verified&&<p className="text-xs text-muted-foreground">WORM güvencesi doğrulanmış nesne kilidi gerektirir; yerel dosya depolaması bu güvenceyi sağlamaz.</p>}</>}</section>;
}
