export type ManagedRole = { id:string;code:string;name:string;permissions:string[];memberCount:number;version:string };
export type ManagedSubject = { subjectId:string;roleIds:string[];permissions:string[];version:string };
export const moduleLabels: Record<string,string> = {access:"Kullanıcı ve erişim yönetimi",archive:"Arşiv kayıtları",audit:"Denetim",classification:"Dosya planı ve üstveri",collections:"Koleksiyonlar",documents:"Belgeler",evidence:"Kanıt ve imza",geo:"Coğrafi arşiv","official-correspondence":"Resmî yazışma",operations:"Operasyon yönetimi",organization:"Kurum birimleri","physical-archive":"Fiziksel arşiv",retention:"Saklama, imha ve devir",search:"Arama",workflow:"Görev ve iş akışları"};
export const permissionNames: Record<string,string> = {
"access.admin":"Kullanıcı, rol ve tüm yetkileri yönet", "access.grants.manage":"Belge paylaşım izinlerini yönet", "access.grants.read":"Paylaşım izinlerini görüntüle",
"archive.records.declare":"Belgeyi arşiv kaydı olarak beyan et","archive.records.read":"Arşiv kayıtlarını görüntüle","audit.read":"Denetim kayıtlarını görüntüle",
"classification.manage":"Dosya planı ve üstveri tanımlarını yönet","classification.read":"Sınıflandırma tanımlarını görüntüle","collections.manage":"Koleksiyonları yönet","collections.read":"Koleksiyonları görüntüle",
"documents.cancel":"Belge kaydını iptal et","documents.download":"Belge içeriğini indir","documents.manage.all":"Tüm birimlerde belge yönetimi kapsamı","documents.metadata.write":"Belge üstverisini düzenle","documents.operations.read":"Belge işlem durumunu görüntüle","documents.read":"Belgeleri görüntüle","documents.read.all":"Tüm birimlerin belgelerine eriş","documents.versions.cancel":"Belge sürümünü iptal et","documents.write":"Belge oluştur ve dosya yükle",
"evidence.read":"Kanıt kayıtlarını görüntüle","evidence.timestamp.request":"Zaman damgası talep et","evidence.validate":"Kanıt ve imza doğrula","geo.manage":"Coğrafi ilişkileri yönet","geo.read":"Coğrafi arşivi görüntüle",
"official-correspondence.eyp.inspect":"EYP paketini incele","official-correspondence.eyp.read":"EYP kayıtlarını görüntüle",
"operations.alerts.acknowledge":"Operasyon uyarılarını onayla","operations.alerts.manage":"Uyarı kurallarını yönet","operations.dr.manage":"Felaket kurtarma süreçlerini yönet","operations.read":"Operasyon durumunu görüntüle","operations.reports.read":"Operasyon raporlarını görüntüle","operations.verify":"Bütünlük doğrulaması başlat",
"organization.manage":"Birimleri ve üyelikleri yönet","organization.read":"Birimleri görüntüle","physical-archive.loan":"Ödünç ve zimmet işlemleri yap","physical-archive.manage":"Fiziksel arşivi yönet","physical-archive.manage.all":"Tüm birimlerde fiziksel arşiv yönetimi kapsamı","physical-archive.read":"Fiziksel arşivi görüntüle",
"retention.commissions.manage":"Komisyon görevlendirmelerini yönet","retention.disposition.approve":"İmha kararını onayla","retention.disposition.execute":"Onaylı imhayı uygula","retention.disposition.prepare":"İmha hazırlığı yap","retention.disposition.review":"İmha hazırlığını incele","retention.export":"Devir paketini dışa aktar","retention.holds.manage":"Hukuki bekletmeleri yönet","retention.read":"Saklama ve imha kayıtlarını görüntüle","retention.rules.manage":"Saklama kurallarını yönet","retention.transfers.accept":"Devri teslim al",
"search.read":"Arşivde arama yap","workflow.manage":"İş akışlarını ve görev atamalarını yönet","workflow.read":"Görev ve iş akışlarını görüntüle","workflow.service.complete":"Servis adımını tamamla","workflow.start":"İş akışı başlat","workflow.task.complete":"Yetkili olduğu görevi tamamla"
};
