<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Application/Mbb.Archive.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Domain/Mbb.Archive.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="../Mbb.Archive.Modules.PhysicalArchive.Contracts/Mbb.Archive.Modules.PhysicalArchive.Contracts.csproj" />
    <ProjectReference Include="../Mbb.Archive.Modules.PhysicalArchive.Domain/Mbb.Archive.Modules.PhysicalArchive.Domain.csproj" />
  </ItemGroup>
</Project>
