<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="MSTest.TestAdapter" /><PackageReference Include="MSTest.TestFramework" /><ProjectReference Include="../../src/Modules/Retention/Mbb.Archive.Modules.Retention.Domain/Mbb.Archive.Modules.Retention.Domain.csproj" /><ProjectReference Include="../../src/Modules/Retention/Mbb.Archive.Modules.Retention.Application/Mbb.Archive.Modules.Retention.Application.csproj" /></ItemGroup></Project>
