<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Application/Mbb.Archive.BuildingBlocks.Application.csproj" /><ProjectReference Include="../Mbb.Archive.Modules.AccessControl.Domain/Mbb.Archive.Modules.AccessControl.Domain.csproj" /></ItemGroup></Project>
