<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><PackageReference Include="Microsoft.EntityFrameworkCore.Relational" /><ProjectReference Include="../Mbb.Archive.Modules.Audit.Infrastructure/Mbb.Archive.Modules.Audit.Infrastructure.csproj" /></ItemGroup></Project>
