import { apiGet } from "@/lib/api/api-client";
import { getCurrentUser } from "@/features/access/api/get-current-user";
import { ActionForm } from "@/components/action-form";
import { Panel } from "@/components/ui/page";
import { operationsAction } from "./actions";
import { RecoveryCompletion } from "./recovery-completion";

type Rule = { id: string; code: string; metric: string; threshold: number; evaluationWindow: string; isEnabled: boolean; notificationChannel?: string; notificationTarget: string; lastEvaluatedAt?: string; lastEvaluationError: string };
type Alert = { id: string; deduplicationKey: string; severity: string; status: string; currentValue: number; occurrenceCount: number; openedAt: string; acknowledgedBy?: string; acknowledgementNote?: string };
type Delivery = { id: string; channel: string; target: string; status: string; attemptCount: number; lastError: string; nextAttemptAt?: string; sentAt?: string; providerReference: string };
type Drill = { id: string; backupReference: string; targetEnvironment: string; status: string; targetRpoMinutes: number; targetRtoMinutes: number; actualRpoMinutes?: number; actualRtoMinutes?: number; evidenceReference: string; requestedBy: string; notes: string; startedAt?: string; completedAt?: string };
type History = { id: string; kind: string; actor: string; detail: string; occurredAt: string };
const field = "mt-1 block min-h-10 w-full rounded border bg-background p-2";
const labels: Record<string, string> = { Open: "Açık", Acknowledged: "Üstlenildi", Resolved: "Kapalı", Planned: "Planlandı", Running: "Devam ediyor", Passed: "Başarılı", Failed: "Başarısız", Pending: "Kuyrukta", Sending: "Gönderiliyor", Sent: "Gönderildi", RetryScheduled: "Yeniden denenecek", DeadLettered: "Denemeler tükendi", Critical: "Kritik", Warning: "Uyarı", Info: "Bilgi", Email: "E-posta", Webhook: "Webhook" };
const metrics: Record<string, string> = { dlq_messages: "İşlenemeyen mesajlar", jobs_active: "Etkin işleme işleri", jobs_failed: "Başarısız işleme işleri", index_pending: "Dizine alınmayı bekleyenler", index_dead_letter: "Başarısız dizin işleri", tasks_overdue: "Geciken görevler", loans_overdue: "Geciken ödünçler", security_pending: "Güvenlik taraması bekleyenler", ingestion_rejected: "Reddedilen yüklemeler", outbox_pending: "Yayınlanmayı bekleyen olaylar", outbox_dead_letter: "Yayınlanamayan olaylar", validation_invalid: "Geçersiz kanıtlar", validation_indeterminate: "Sonuçlandırılamayan kanıtlar", unhealthy_components: "Hatalı bileşenler", notification_failure_total: "Başarısız bildirimler", recovery_drill_failures: "Başarısız kurtarma tatbikatları" };
const eventLabels: Record<string, string> = { "alert.opened": "Alarm açıldı", "alert.resolved": "Alarm kapandı", "notification.queued": "Bildirim kuyruğa alındı", "notification.sent": "Bildirim gönderildi", "notification.failed": "Bildirim gönderilemedi", "notification.retry_requested": "Yeniden deneme istendi", "rule.enabled_changed": "Kural durumu değişti" };
function Op({ operation, id }: { operation: string; id?: string }) { return <><input type="hidden" name="operation" value={operation} />{id && <input type="hidden" name="id" value={id} />}</>; }
export async function OperationsControls() {
  const user = await getCurrentUser();
  const can = (permission: string) => !!user?.isAuthenticated && (user.isBootstrapAdministrator || user.permissions.includes(permission));
  const manage = can("operations.alerts.manage"); const dr = can("operations.dr.manage");
  const [rules, alerts, drills, status, deliveries, history] = await Promise.all([
    apiGet<Rule[]>("/operations/alert-rules", { cache: "no-store" }), apiGet<Alert[]>("/operations/alerts", { cache: "no-store" }),
    apiGet<Drill[]>("/operations/recovery-drills", { cache: "no-store" }), apiGet<{ deliveryEnabled: boolean; metrics: string[]; emailConfigured: boolean; webhookConfigured: boolean }>("/operations/automation/status", { cache: "no-store" }),
    manage ? apiGet<Delivery[]>("/operations/notifications", { cache: "no-store" }) : Promise.resolve([]),
    apiGet<History[]>("/operations/automation/history", { cache: "no-store" }),
  ]);
  return <>
    <Panel title="Alarm kuralları" padded description="Ölçümler 30 saniyede bir değerlendirilir. Eşik pencere boyunca aşılırsa alarm açılır; ölçüm kesintisi pencereyi sıfırlar.">
      {manage && <div className="mb-5 max-w-sm"><ActionForm action={operationsAction} label="Şimdi değerlendir"><Op operation="evaluate" /></ActionForm></div>}
      <ul className="divide-y">{rules.map(rule => <li key={rule.id} className="flex flex-wrap items-center justify-between gap-4 py-3"><div><p className="font-medium">{rule.code} · {rule.isEnabled ? "Etkin" : "Pasif"}</p><p className="text-sm text-muted-foreground">{metrics[rule.metric] ?? rule.metric} · eşik {rule.threshold} · pencere {rule.evaluationWindow}</p><p className="text-xs text-muted-foreground">{rule.notificationChannel ? `${labels[rule.notificationChannel]} · ${rule.notificationTarget}` : "Yalnız uygulama içi alarm"} · {rule.lastEvaluatedAt ? `Son değerlendirme: ${new Date(rule.lastEvaluatedAt).toLocaleString("tr-TR")}` : "Henüz değerlendirilmedi"}</p>{rule.lastEvaluationError && <p className="text-sm text-destructive">{rule.lastEvaluationError}</p>}</div>{manage && <ActionForm action={operationsAction} label={rule.isEnabled ? "Pasifleştir" : "Etkinleştir"}><Op operation="rule-enabled" id={rule.id} /><input type="hidden" name="enabled" value={String(!rule.isEnabled)} /></ActionForm>}</li>)}</ul>
      {!rules.length && <p className="text-sm text-muted-foreground">Henüz alarm kuralı tanımlanmamış.</p>}
      {manage && <details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-medium">Yeni alarm kuralı</summary><div className="mt-4 max-w-2xl"><ActionForm action={operationsAction} label="Alarm kuralını oluştur"><Op operation="create-rule" /><div className="grid gap-3 sm:grid-cols-2">
        <label className="text-sm">Kural kodu<input name="code" className={field} required maxLength={150} /></label>
        <label className="text-sm">Ölçüm<select name="metric" className={field}>{status.metrics.map(metric => <option key={metric} value={metric}>{metrics[metric] ?? metric}</option>)}</select></label>
        <label className="text-sm">Karşılaştırma<select name="comparison" className={field}><option value="0">Büyüktür</option><option value="1">Büyük veya eşittir</option><option value="2">Eşittir</option><option value="3">Küçüktür</option></select></label>
        <label className="text-sm">Eşik<input name="threshold" type="number" step="any" min="0" required className={field} /></label>
        <label className="text-sm">Pencere (dakika)<input name="window" type="number" min="1" max="1440" defaultValue="5" required className={field} /></label>
        <label className="text-sm">Önem<select name="severity" className={field}><option value="1">Uyarı</option><option value="2">Kritik</option><option value="0">Bilgi</option></select></label>
        <label className="text-sm">Bildirim kanalı<select name="channel" className={field}><option value="">Yalnız uygulama içi</option><option value="0">E-posta</option><option value="1">Webhook</option></select></label>
        <label className="text-sm">Bildirim hedefi<input name="target" maxLength={1000} className={field} /><span className="text-xs text-muted-foreground">Kanal seçildiğinde e-posta veya izinli HTTPS adresi gerekir.</span></label>
      </div></ActionForm></div></details>}
    </Panel>
    <Panel title="Etkin alarmlar" padded><ul className="divide-y">{alerts.map(alert => <li key={alert.id} className="space-y-3 py-4"><p className="font-medium">{alert.deduplicationKey} · {labels[alert.severity]} · {labels[alert.status] ?? alert.status}</p><p className="text-sm">Son değer: {alert.currentValue} · Gözlem: {alert.occurrenceCount}</p>{alert.acknowledgedBy && <p className="text-sm">Üstlenen: {alert.acknowledgedBy} · {alert.acknowledgementNote}</p>}<div className="grid gap-3 sm:grid-cols-2">{alert.status === "Open" && can("operations.alerts.acknowledge") && <ActionForm action={operationsAction} label="Alarmı üstlen"><Op operation="acknowledge" id={alert.id} /><label className="text-sm">Üstlenme notu<input name="note" maxLength={2000} className={field} /></label></ActionForm>}{manage && <ActionForm action={operationsAction} label="Alarmı kapat"><Op operation="resolve" id={alert.id} /><p className="text-xs text-muted-foreground">Koşul sürüyorsa sonraki değerlendirme yeniden alarm açar.</p></ActionForm>}</div></li>)}</ul>{!alerts.length && <p className="text-sm text-muted-foreground">Etkin alarm yok.</p>}</Panel>
    {manage && <Panel title="Bildirim teslimleri" padded><p className="mb-4 text-sm">{status.deliveryEnabled ? "Dış bildirim gönderimi etkin." : "Dış bildirim gönderimi kapalı. Kuyruk kayıtları korunur; sağlayıcı ve gönderim yapılandırması etkinleştirilince işlenir."}</p><p className="mb-4 text-sm text-muted-foreground">E-posta: {status.emailConfigured ? "Yapılandırılmış" : "Yapılandırılmamış"} · Webhook: {status.webhookConfigured ? "İzinli sağlayıcı tanımlı" : "Sağlayıcı tanımlı değil"}. Gerçek teslim sonucu her kayıt için ayrıca izlenir.</p><ul className="divide-y">{deliveries.map(item => <li key={item.id} className="space-y-2 py-3"><p className="break-all text-sm">{labels[item.channel]} · {item.target} · {labels[item.status]} · {item.attemptCount} deneme</p>{item.lastError && <p className="text-sm text-destructive">{item.lastError}</p>}{item.sentAt && <p className="text-xs">Teslim: {new Date(item.sentAt).toLocaleString("tr-TR")} {item.providerReference ? `· Sağlayıcı: ${item.providerReference}` : ""}</p>}{item.nextAttemptAt && <p className="text-xs text-muted-foreground">Sıradaki deneme: {new Date(item.nextAttemptAt).toLocaleString("tr-TR")}</p>}{item.status === "DeadLettered" && <ActionForm action={operationsAction} label="Yeniden kuyruğa al"><Op operation="retry" id={item.id} /></ActionForm>}</li>)}</ul>{!deliveries.length && <p className="text-sm text-muted-foreground">Bildirim kaydı yok.</p>}</Panel>}
    <Panel title="Geri dönüş tatbikatları" padded description="İzole ortamda gerçek geri yükleme, belge bütünlüğü, denetim zinciri ve erişim kontrollerinin sonuçlarını kaydedin.">
      {dr && <details className="mb-5"><summary className="cursor-pointer font-medium">Tatbikat planla</summary><div className="mt-4 max-w-xl"><ActionForm action={operationsAction} label="Tatbikat planını kaydet"><Op operation="dr-plan" /><label className="text-sm">Yedek referansı<input name="backup" required maxLength={1000} className={field} /></label><label className="text-sm">İzole hedef ortam<input name="environment" required maxLength={300} className={field} /></label><label className="text-sm">Hedef RPO (dakika)<input name="rpo" type="number" min="1" required className={field} /></label><label className="text-sm">Hedef RTO (dakika)<input name="rto" type="number" min="1" required className={field} /></label></ActionForm></div></details>}
      <ul className="divide-y">{drills.map(item => <li key={item.id} className="space-y-3 py-4"><p className="font-medium">{item.backupReference} · {labels[item.status]}</p><p className="text-sm">{item.targetEnvironment} · Hedef RPO/RTO: {item.targetRpoMinutes}/{item.targetRtoMinutes} dakika{item.actualRpoMinutes != null ? ` · Ölçülen: ${item.actualRpoMinutes}/${item.actualRtoMinutes}` : ""}</p><p className="text-xs text-muted-foreground">Planlayan: {item.requestedBy}{item.completedAt ? ` · Bitiş: ${new Date(item.completedAt).toLocaleString("tr-TR")}` : ""}</p>{item.notes && <p className="whitespace-pre-wrap text-sm">{item.notes}</p>}{item.evidenceReference && <p className="break-all text-sm">Kanıt: {item.evidenceReference}</p>}{dr && item.status === "Planned" && <ActionForm action={operationsAction} label="Tatbikatı başlat"><Op operation="dr-start" id={item.id} /></ActionForm>}{dr && item.status === "Running" && <RecoveryCompletion id={item.id} targetRpo={item.targetRpoMinutes} targetRto={item.targetRtoMinutes} />}</li>)}</ul>{!drills.length && <p className="text-sm text-muted-foreground">Henüz tatbikat kaydı yok.</p>}
    </Panel>
    <Panel title="Alarm ve bildirim geçmişi" padded><ul className="max-h-96 divide-y overflow-auto">{history.map(item => <li key={item.id} className="py-3 text-sm"><p>{eventLabels[item.kind] ?? item.kind} · {item.actor} · {new Date(item.occurredAt).toLocaleString("tr-TR")}</p><p className="text-muted-foreground">{item.detail}</p></li>)}</ul>{!history.length && <p className="text-sm text-muted-foreground">Henüz olay kaydı yok.</p>}</Panel>
  </>;
}
