// <auto-generated />
using System;
using System.Collections.Generic;
using Mbb.Archive.Modules.Geo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mbb.Archive.Modules.Geo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GeoDbContext))]
    partial class GeoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("geo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Entities.GeoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_reference");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("feature_id");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geojson");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("layer_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BoundingBox", "Mbb.Archive.Modules.Geo.Domain.Entities.GeoEntity.BoundingBox#GeoBoundingBox", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("MaxLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_latitude");

                            b1.Property<double>("MaxLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("max_longitude");

                            b1.Property<double>("MinLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_latitude");

                            b1.Property<double>("MinLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("min_longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_geo_entities_type");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_geo_entities_name");

                    b.HasIndex("Provider", "LayerName", "FeatureId")
                        .IsUnique()
                        .HasDatabaseName("ux_geo_entities_provider_layer_feature");

                    b.ToTable("entities", "geo");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Relations.DocumentGeoRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("GeoEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("geo_entity_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("relation_type");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_geo_relations_document");

                    b.HasIndex("GeoEntityId")
                        .HasDatabaseName("ix_geo_relations_entity");

                    b.ToTable("document_relations", "geo");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Services.GeoBasemap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("attribution");

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("center_latitude");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("center_longitude");

                    b.Property<string>("TileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("tile_url");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("updated_by");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<int>("Zoom")
                        .HasColumnType("integer")
                        .HasColumnName("zoom");

                    b.HasKey("Id");

                    b.ToTable("basemap", "geo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attribution = "",
                            CenterLatitude = 38.355200000000004,
                            CenterLongitude = 38.3095,
                            TileUrl = "",
                            UpdatedBy = "system",
                            Version = 1L,
                            Zoom = 12
                        });
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Services.GeoService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("PasswordCipher")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("password_cipher");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("services", "geo");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Services.GeoServiceLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ImageFormat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_format");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsQueryable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_queryable");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("layer_name");

                    b.Property<string>("NameAttribute")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_attribute");

                    b.Property<int>("OpacityPercent")
                        .HasColumnType("integer")
                        .HasColumnName("opacity_percent");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<bool>("VisibleByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_by_default");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId", "LayerName")
                        .IsUnique();

                    b.ToTable("service_layers", "geo");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Infrastructure.Persistence.GeoOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "geo");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Relations.DocumentGeoRelation", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Geo.Domain.Entities.GeoEntity", null)
                        .WithMany()
                        .HasForeignKey("GeoEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Services.GeoServiceLayer", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Geo.Domain.Services.GeoService", null)
                        .WithMany("Layers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Geo.Domain.Services.GeoService", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
