<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Application/Mbb.Archive.BuildingBlocks.Application.csproj" /><ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Domain/Mbb.Archive.BuildingBlocks.Domain.csproj" /><ProjectReference Include="../../Archive/Mbb.Archive.Modules.Archive.Contracts/Mbb.Archive.Modules.Archive.Contracts.csproj" /><ProjectReference Include="../Mbb.Archive.Modules.Retention.Contracts/Mbb.Archive.Modules.Retention.Contracts.csproj" /><ProjectReference Include="../Mbb.Archive.Modules.Retention.Domain/Mbb.Archive.Modules.Retention.Domain.csproj" /></ItemGroup></Project>
