// <auto-generated />
using System;
using Mbb.Archive.Modules.Workflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mbb.Archive.Modules.Workflow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    [Migration("20260909195357_WorkItemAssignment")]
    partial class WorkItemAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("definitions", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Permission")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permission");

                    b.Property<string>("ServiceOperation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("service_operation");

                    b.Property<int?>("SlaMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sla_minutes");

                    b.Property<int?>("TimerDelayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("timer_delay_minutes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("nodes", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("condition_expression");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_node_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_node_id");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("transitions", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<Guid>("CurrentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_node_id");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("WakeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wake_at");

                    b.HasKey("Id");

                    b.ToTable("instances", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Key")
                        .IsUnique();

                    b.ToTable("variables", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assigned_by");

                    b.Property<string>("AssigneeSubjectId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assignee_subject_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("completed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("integer")
                        .HasColumnName("escalation_level");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("outcome");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permission");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Status", "DueAt");

                    b.ToTable("work_items", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Infrastructure.WorkflowOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "workflow");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowNode", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowDefinition", null)
                        .WithMany("Nodes")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowTransition", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowDefinition", null)
                        .WithMany("Transitions")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowVariable", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowInstance", null)
                        .WithMany("Variables")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowWorkItem", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowInstance", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Definitions.WorkflowDefinition", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Workflow.Domain.Instances.WorkflowInstance", b =>
                {
                    b.Navigation("Variables");

                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
