// <auto-generated />
using System;
using Mbb.Archive.Modules.PhysicalArchive.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mbb.Archive.Modules.PhysicalArchive.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PhysicalArchiveDbContext))]
    partial class PhysicalArchiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("physical_archive")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Folders.PhysicalFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("barcode");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DigitalDossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("digital_dossier_id");

                    b.Property<string>("FilePlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_plan_code");

                    b.Property<DateTimeOffset?>("LastMovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_moved_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("OwnerUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("DigitalDossierId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerUnitId", "FilePlanCode");

                    b.ToTable("folders", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Folders.PhysicalFolderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DisposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disposed_at");

                    b.Property<string>("DisposedBy")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("disposed_by");

                    b.Property<Guid?>("DispositionEvidenceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("disposition_evidence_document_id");

                    b.Property<Guid?>("DispositionProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("disposition_process_id");

                    b.Property<string>("DispositionReference")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("disposition_reference");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FolderId", "DocumentId")
                        .IsUnique();

                    b.ToTable("folder_documents", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Loans.PhysicalLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BorrowerSubjectId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("borrower_subject_id");

                    b.Property<DateTimeOffset>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<string>("CheckedOutBy")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("checked_out_by");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid")
                        .HasColumnName("folder_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("purpose");

                    b.Property<string>("ReturnNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("return_note");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("FolderId", "Status");

                    b.ToTable("loans", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Locations.ArchiveLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("barcode");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("locations", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Locations.ArchiveLocationTypeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsCapacity")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_capacity");

                    b.Property<bool>("CanStoreFolder")
                        .HasColumnType("boolean")
                        .HasColumnName("can_store_folder");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_built_in");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("location_types", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Infrastructure.Persistence.Outbox.PhysicalArchiveOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "physical_archive");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Folders.PhysicalFolderDocument", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.PhysicalArchive.Domain.Folders.PhysicalFolder", null)
                        .WithMany("Documents")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.PhysicalArchive.Domain.Folders.PhysicalFolder", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
