// <auto-generated />
using System;
using Mbb.Archive.Modules.OfficialCorrespondence.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mbb.Archive.Modules.OfficialCorrespondence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OfficialCorrespondenceDbContext))]
    [Migration("20260902202648_InitialOfficialCorrespondence")]
    partial class InitialOfficialCorrespondence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("official_correspondence")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mbb.Archive.Modules.OfficialCorrespondence.Domain.Eyp.EypPackageInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("DocumentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_version_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("InspectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspected_at");

                    b.Property<string>("OfficialReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("official_report_json");

                    b.Property<string>("OfficialValidationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("official_validation_status");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("package_sha256")
                        .IsFixedLength();

                    b.Property<int>("PartCount")
                        .HasColumnType("integer")
                        .HasColumnName("part_count");

                    b.Property<int>("RelationshipCount")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_count");

                    b.Property<string>("StructuralReportJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("structural_report_json");

                    b.Property<string>("StructuralStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("structural_status");

                    b.HasKey("Id");

                    b.HasIndex("PackageSha256");

                    b.ToTable("eyp_inspections", "official_correspondence");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.OfficialCorrespondence.Infrastructure.Persistence.OfficialCorrespondenceOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "official_correspondence");
                });
#pragma warning restore 612, 618
        }
    }
}
