<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="MSTest.TestAdapter" /><PackageReference Include="MSTest.TestFramework" /><ProjectReference Include="../../src/Modules/Archive/Mbb.Archive.Modules.Archive.Domain/Mbb.Archive.Modules.Archive.Domain.csproj" /></ItemGroup></Project>
