// <auto-generated />
using System;
using Mbb.Archive.Modules.Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mbb.Archive.Modules.Documents.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260905195747_AddDigitalDossiers")]
    partial class AddDigitalDossiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("uuid")
                        .HasColumnName("dossier_id");

                    b.Property<string>("FilePlanCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_plan_code");

                    b.Property<Guid?>("OwnerUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_unit_id");

                    b.Property<string>("OwnerUnitPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("owner_unit_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documents_created_at");

                    b.HasIndex("DossierId");

                    b.HasIndex("FilePlanCode")
                        .HasDatabaseName("ix_documents_file_plan_code");

                    b.HasIndex("OwnerUnitPath")
                        .HasDatabaseName("ix_documents_owner_unit_path");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.ToTable("documents", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Documents.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256_hash")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_key");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_document_versions_sha256");

                    b.HasIndex("DocumentId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_document_versions_document_version");

                    b.ToTable("document_versions", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Dossiers.DigitalDossier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePlanCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_plan_code");

                    b.Property<Guid>("FilePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_plan_id");

                    b.Property<Guid>("FilePlanItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_plan_item_id");

                    b.Property<string>("FilePlanTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_plan_title");

                    b.Property<string>("FilePlanVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file_plan_version");

                    b.Property<Guid>("OwnerUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_unit_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUnitId", "FilePlanId", "FilePlanCode", "Year");

                    b.ToTable("digital_dossiers", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Ingestions.DocumentFileIngestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_content_type");

                    b.Property<long>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("concurrency_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeclaredSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("declared_size_bytes");

                    b.Property<string>("DetectedMimeType")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("detected_mime_type");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OriginalStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("original_storage_key");

                    b.Property<DateTimeOffset?>("OriginalStoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("original_stored_at");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rejection_code");

                    b.Property<string>("RejectionDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_detail");

                    b.Property<DateTimeOffset?>("SecurityScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("security_scanned_at");

                    b.Property<string>("SecurityScanner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("security_scanner");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("sha256_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("StagedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("staged_at");

                    b.Property<string>("StagingStorageKey")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("staging_storage_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long?>("StoredSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("stored_size_bytes");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submitted_by");

                    b.Property<string>("VersionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("version_reason");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_file_ingestions_document_id");

                    b.HasIndex("Sha256Hash")
                        .HasDatabaseName("ix_file_ingestions_sha256");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_file_ingestions_status");

                    b.ToTable("file_ingestions", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Infrastructure.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_inbox_processed_at");

                    b.ToTable("inbox_messages", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("ix_outbox_lease");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_dispatch");

                    b.ToTable("outbox_messages", "documents");
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Documents.Document", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Documents.Domain.Dossiers.DigitalDossier", null)
                        .WithMany()
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Documents.DocumentVersion", b =>
                {
                    b.HasOne("Mbb.Archive.Modules.Documents.Domain.Documents.Document", null)
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mbb.Archive.Modules.Documents.Domain.Documents.Document", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
