import Link from "next/link";
import { UserRound, ShieldCheck, Building2, LogOut } from "lucide-react";
import { getCurrentUser } from "@/features/access/api/get-current-user";
import { getArchiveUnits } from "@/features/dossiers/api/dossiers";
import { PageHeader } from "@/components/ui/page";
export const metadata = { title: "Profilim" };
export default async function ProfilePage() {
  const user = await getCurrentUser();
  const units = user?.isAuthenticated ? await getArchiveUnits().then(items => ({ items, error: false })).catch(() => ({ items: [], error: true })) : { items: [], error: false };
  return <div className="space-y-5">
    <PageHeader title="Profilim" description="Hesap bilgilerinizi, arşiv erişiminizi ve rollerinizi görüntüleyin." actions={<form action="/api/auth/logout" method="post"><button className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2 text-sm hover:bg-muted"><LogOut className="size-4" />Çıkış yap</button></form>} />
    {!user?.isAuthenticated ? <div className="rounded-xl border border-border bg-card p-6"><p>Hesap bilgisi alınamadı.</p><Link href="/login" className="mt-3 inline-block text-primary underline">Giriş sayfasına dön</Link></div> : <>
      <div className="grid items-start gap-5 lg:grid-cols-[340px_minmax(0,1fr)]">
        <section aria-label="Hesap bilgileri" className="rounded-xl border border-border bg-card p-6"><span className="mb-4 inline-flex rounded-2xl bg-primary/10 p-4 text-primary"><UserRound className="size-8" /></span><h2 className="text-lg font-semibold">{user.authenticationMode === "Development" ? "Geliştirme hesabı" : "Kurum hesabı"}</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-muted-foreground">Kullanıcı kimliği</dt><dd className="mt-1 break-all font-medium">{user.subject}</dd></div><div><dt className="text-muted-foreground">Oturum türü</dt><dd className="mt-1">{user.authenticationMode === "Development" ? "Geliştirme kimliği" : "Doğrulanmış kurum oturumu"}</dd></div></dl><p className="mt-5 border-t border-border pt-4 text-xs leading-6 text-muted-foreground">{user.authenticationMode === "Development" ? "LDAP bağlantısı hazırlık aşamasında. Giriş ekranına yazılan bilgiler bu hesabın kimliğini değiştirmez." : "Kişisel bilgiler ve parola kurum kimlik sistemi tarafından yönetilir."}</p></section>
        <div className="space-y-5"><section aria-label="Roller ve yetkiler" className="rounded-xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="size-5 text-primary" />Roller ve yetkiler</h2><div className="mt-4 flex flex-wrap gap-2">{user.roles.length ? user.roles.map(role => <span key={role} className="rounded-lg bg-muted px-3 py-2 text-sm">{role}</span>) : <p className="text-sm text-muted-foreground">Atanmış rol bulunmuyor.</p>}</div>{user.isBootstrapAdministrator && <p className="mt-3 text-sm">Başlangıç yöneticisi erişimi etkin.</p>}<details className="mt-4 border-t border-border pt-4"><summary className="cursor-pointer text-sm">Etkin izinler ({user.permissions.length})</summary><ul className="mt-3 grid gap-2 sm:grid-cols-2">{user.permissions.map(permission => <li key={permission} className="break-all rounded bg-muted/40 px-3 py-2 text-xs">{permission}</li>)}</ul></details></section>
          <section aria-label="Arşiv erişimi" className="rounded-xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><Building2 className="size-5 text-primary" />Erişebildiğim birim arşivleri</h2>{units.error ? <p role="alert" className="mt-4 text-sm text-destructive">Birim bilgileri alınamadı. Sayfayı yenileyerek tekrar deneyin.</p> : units.items.length ? <ul className="mt-4 divide-y divide-border">{units.items.map(unit => <li key={unit.id} className="py-3"><Link href={`/documents?ownerUnitId=${encodeURIComponent(unit.id)}`} className="text-sm font-medium text-primary hover:underline">{unit.name}</Link><p className="mt-1 text-xs text-muted-foreground">{unit.isPrimary ? "Birincil birim · " : ""}{unit.canManageDocuments ? "Dijital belge yönetimi" : "Dijital belge görüntüleme"}{unit.canManagePhysical ? " · Fiziksel arşiv yönetimi" : ""}</p></li>)}</ul> : <p className="mt-4 text-sm text-muted-foreground">Erişilebilir birim arşivi bulunmuyor.</p>}</section>
        </div>
      </div>
    </>}
  </div>;
}
