<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Presentation/Mbb.Archive.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="../Mbb.Archive.Modules.Operations.Application/Mbb.Archive.Modules.Operations.Application.csproj" />
  </ItemGroup>
</Project>
