<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Application/Mbb.Archive.BuildingBlocks.Application.csproj" /><ProjectReference Include="../../../BuildingBlocks/Mbb.Archive.BuildingBlocks.Domain/Mbb.Archive.BuildingBlocks.Domain.csproj" /><ProjectReference Include="../../Documents/Mbb.Archive.Modules.Documents.Contracts/Mbb.Archive.Modules.Documents.Contracts.csproj" /><ProjectReference Include="../Mbb.Archive.Modules.Archive.Contracts/Mbb.Archive.Modules.Archive.Contracts.csproj" /><ProjectReference Include="../Mbb.Archive.Modules.Archive.Domain/Mbb.Archive.Modules.Archive.Domain.csproj" /></ItemGroup></Project>
